// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znmeyumbgnsffshdrbie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpubWV5dW1iZ25zZmZzaGRyYmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzU2NTIsImV4cCI6MjA1NDM1MTY1Mn0.TX26z7SLYOR1hljo8p3ANtDUAOBallps5VGOA-Rka34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);